version: '3'

services:

  web:
    container_name: odoo-web
    image: ${WEB_IMAGE_NAME}
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./files/config:/etc/odoo
      - ./files/addons:/mnt/extra-addons
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"

  db:
    container_name: db # ðŸ‘ˆ Nombre que odoo.conf puede resolver
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-db-data:
  odoo-web-data:
