services:
  web:
    image: odoo:17.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8069"
      - "8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./files/config:/etc/odoo
      - ./files/addons:/mnt/extra-addons
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    networks:
      - odoonet
      - dokploy-network
    labels:
      # Habilitar Traefik
      - "traefik.enable=true"
      # Router para Odoo
      - "traefik.http.routers.odoo-web.rule=Host(`odoo.consulting.docker.consulting-sac.com.pe`)"
      - "traefik.http.routers.odoo-web.entrypoints=websecure"
      - "traefik.http.routers.odoo-web.tls=true"
      - "traefik.http.routers.odoo-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.odoo-web.loadbalancer.server.port=8069"
      # Middleware CORS
      - "traefik.http.middlewares.odoo-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS,PATCH"
      - "traefik.http.middlewares.odoo-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.odoo-cors.headers.accesscontrolalloworiginlist=https://hotel.calendar.consulting-sac.consulting-sac.com.pe"
      - "traefik.http.middlewares.odoo-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.odoo-cors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.odoo-cors.headers.addvaryheader=true"
      # Aplicar middleware CORS al router
      - "traefik.http.routers.odoo-web.middlewares=odoo-cors"

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoonet

volumes:
  odoo-web-data:
  odoo-db-data:


networks:
  odoonet:
  dokploy-network:
    external: true
