version: '3'

services:

  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069" # Puerto público de Odoo
      - "${WEBSOCKET_PORT}:8072" # Para LiveChat / longpolling
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./files/config:/etc/odoo # Aquí va tu odoo.conf
      - ./files/addons:/mnt/extra-addons
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"

  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-db-data:
  odoo-web-data:
