services:
  web:
    image: odoo:17.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8070:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./files/config:/etc/odoo
      - ./files/addons:/mnt/extra-addons
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    networks:
      - odoonet
    labels:
      # Aplicar middleware CORS desde file provider (middlewares.yml)
      - "traefik.http.routers.web-odoohotelfullproyect-odoo17-pt92aa.middlewares=cors-headers@file"

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoonet

volumes:
  odoo-web-data:
  odoo-db-data:


networks:
  odoonet:
