version: '3'

services:
  web:
    container_name: odoo-web
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8070:8069" # Puerto externo para Odoo
      - "8072:8072" # WebSocket / Longpolling
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./files/config:/etc/odoo
      - ./files/addons:/mnt/extra-addons
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    networks:
      - odoonet

  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
    ports:
      - "5434:5432" # Puerto externo diferente para evitar conflicto con otras DB
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoonet

volumes:
  odoo-web-data:
  odoo-db-data:


networks:
  odoonet:
